name: rest_server
description: A simple REST framework containing a wrapper http server adding CORS headers and a tree-implementation taking an HTTP handler for every path.
dependencies:
  logging: any
dev_dependencies:
  unittest: any
